<!doctype html>
<html lang="tr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.css" type="text/css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/custom.css" type="text/css">
    <link rel="stylesheet" href="css/fadein.css">
    <link rel="stylesheet" href="css/style4.css" type="text/css">
    <title>Mustafa Çakmak | Anasayfa</title>
    <style type="text/css">
        .slide-top {
            -webkit-animation: slide-top 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0.2s both;
            animation: slide-top 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0.2s both;
        }
        /* ----------------------------------------------
   * Generated by Animista on 2019-1-21 13:33:6
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

        /**
         * ----------------------------------------
         * animation slide-top
         * ----------------------------------------
         */
        @-webkit-keyframes slide-top {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
            }
            100% {
                -webkit-transform: translateY(-100px);
                transform: translateY(-100px);
            }
        }
        @keyframes slide-top {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
            }
            100% {
                -webkit-transform: translateY(-100px);
                transform: translateY(-100px);
            }
        }




    </style>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Roboto" rel="stylesheet">
</head>
<body>

<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar" class="d-none d-sm-none d-md-block">
        <div class="sidebar-header">
            <h3 style="font-size: 2rem;">mustafa çakmak</h3>
            <strong>mç</strong>
            <button type="button" id="sidebarCollapse" class="btn btn-secondary">
                <i class="fas fa-align-left"></i>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>
        </div>

        <ul class="list-unstyled components d-sm-none d-md-block">
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="">
                    <i class="fas fa-home"></i>
                    İncelemeler
                </a>

            </li>
            <li>
                <a href="#">
                    <i class="fas fa-copy"></i>
                    Karalamalar
                </a>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-users"></i>
                    Toplumsal
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Page 1</a>
                    </li>
                    <li>
                        <a href="#">Page 2</a>
                    </li>
                    <li>
                        <a href="#">Page 3</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-image"></i>
                    Objektifimden
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-question"></i>
                    Hakkımda
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-paper-plane"></i>
                    İletişim
                </a>
            </li>
        </ul>

    </nav>

    <!-- Page Content  -->
    <main id="content">
        <!-- Mobil Menu -->
        <nav class="navbar navbar-dark bg-dark d-sm-block d-md-none">
            <!-- Navbar content -->
            <h2 style="color:white">mustafa çakmak</h2>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li>
                        <a class="navbar-brand" href="#">İncelemeler</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Karalamalar <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Toplumsal
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="https://www.google.com">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Hakkımda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">İletişim</a>
                    </li>
                </ul>
            </div>
        </nav>